#!/bin/sh

true=0
false=1

print_usage() {
	echo 'Usage:'
	echo '  git install-hooks [--status]'
	echo '  git install-hooks --help'
	echo '  git install-hooks <git-project> [<other project> ...]'
	echo '  git install-hooks --init'
	exit 1
}

script_location=$(dirname "$0")

is_init=false
is_status=false
is_silent=$false
is_help=false

print() {
	msg=$@
	if [ $is_silent == $false ]; then
		echo $msg
	fi
}

for var in "$@"
do
	if [ "$var" == "--init" ]; then
		is_init=true
	fi
	if [ "$var" == "--status" ]; then
		is_status=true
	fi
	if [ "$var" == "--help" ]; then
		is_help=true
	fi
	if [ "$var" == "--silent" ]; then
		is_silent=$true
	fi
done

if [ "$1" == "" ]; then
	is_status=true
fi

if [ $is_help == "true" ]; then
	print_usage
fi

hooks_path="$script_location"/git-templates/hooks

if [ $is_status == "true" ]; then
	current_global=$(git config --global core.hooksPath)
	current_local=$(git config core.hooksPath)

	has_issues=$false

	if [ "$current_global" == "$hooks_path" ]; then
		print "Global hook installed."
	else
		print "Global hook is not installed."
		has_issues=$true
	fi

	if [ "$current_local" != "$current_global" ]; then
		print "Local hooksPath has overridden global hook."
		print "Local hooksPath: $current_local"
		has_issues=$true
	fi

	print

	additional_hooks=$(git config --get-all fizker.hooksPath)
	if [ "$additional_hooks" == "" ]; then
		print "No additional hooks"
	else
		print "Additional hooks:"
		print $(node -e "
			console.log(process.argv[1].split(/\n/g).map(x => '- ' + x).join('\n'))
		" "$additional_hooks")
	fi

	if [ $has_issues == $true ]; then
		print
		print Resolve the issues by running '`git-install-hooks .`'
		exit 1
	fi

	exit 0
fi

if [ $is_init == "true" ]; then
	git config --global core.hooksPath "$hooks_path"

	exit 0
fi

for target_repo in "$@"
do
	pushd "$target_repo" &> /dev/null

	existing_hooks_path=$(git config core.hooksPath)
	if [ "$existing_hooks_path" != "" ] && [ "$existing_hooks_path" != "$hooks_path" ];
	then
		set +e
		_=$(git config --get fizker.hooksPath "^$existing_hooks_path$")
		has_registered_hook=$?
		set -e

		if [ $has_registered_hook != 0 ]; then
			git config --add fizker.hooksPath "$existing_hooks_path"
		fi
		git config --unset core.hooksPath
	fi

	popd &> /dev/null
done
