#!/bin/sh

if [ "$1" == "" ]; then
	echo 'Usage:'
	echo '  git install-hooks <git-project> [<other project> ...]'
	echo '  git install-hooks --init'
	exit 1
fi

script_location=$(dirname "$0")

is_init=false

for var in "$@"
do
	if [ "$var" == "--init" ]; then
		is_init=true
	fi
done

if [ $is_init == "true" ]; then
	hooks_location="$script_location"/git-templates/hooks

	git config --global core.hooksPath "$hooks_location"

	exit 0
fi

for target_repo in "$@"
do
	pushd "$target_repo"

	hooks_path=$(git config core.hooksPath)
	if [ "$hooks_path" != "" ];
	then
		git config --add fizker.hooksPath "$hooks_path"
		git config --unset core.hooksPath
	fi

	popd
done
