#!/bin/sh

app=$1

if [ "$app" = '' ]; then
	app='Xcode'
fi

until [ -e ".git" ]; do
	cd ..
done

read -d "" node_script <<EOF
	var lines = ''
	process.stdin.on('data', function(data) {
		lines += data.toString()
	})
	process.stdin.on('end', function() {
		var conflicts = lines
			.split('\\\n')
			.map(function(line) {
				return line.trim()
			})
			.filter(function(line) {
				return line.indexOf('UU') == 0
			})
			.map(function(line) {
				return line.substring(2)
					.trim()
			})
			.map(function(line) {
				return '"' + line +'"'
			})
			.join('\\\n')
		console.log(conflicts)
	})
EOF

git status --porcelain | \
	grep -E ^UU | \
	node -e "$node_script" | \
	xargs open -a "$app"
