#!/bin/sh

script_location=$(dirname "$0")
hook_name=$(basename "$1")

if ! hash node 2> /dev/null
then
	echo "Node not found, skipping $hook_name hook"
	exit 0
fi

set -e

"$script_location"/check-old-style-setup execute-hook

hook_path="$script_location"/"$hook_name"/hook

git_root=$(git rev-parse --show-toplevel)

"$script_location"/../../swift/bin/git-scripts test-all --include-hooks-path \
	--command "$hook_path" \
	--command "$git_root"/.git/hooks/"$hook_name" \
	--command "$git_root"/.git/hooks/"$hook_name".local \
	"${@:2}"
