#!/bin/sh

script_location=$(dirname "$0")
source "$script_location"/../bash/colors.sh

cat /etc/pam.d/sudo | grep pam_tid.so > /dev/null \
	|| echo ${red}'TouchID have not been set up for validating `sudo`. Check the `scripts/macos/readme.md` file for info on how to set it up.'${reset}
