#!/bin/sh

hook_name=post-rewrite

set -e

script_location=$(dirname "$0")

base_dir=$(cat "$script_location"/script_base)

"$base_dir"/$hook_name/hook "$@"

if [ -e "$script_location"/$hook_name.local ]; then
	"$script_location"/$hook_name.local "$@"
fi
