#!/bin/sh

hook_name=pre-applypatch

set -e

script_location=$(dirname "$0")

base_dir=$(cat "$script_location"/script_base)

"$base_dir"/$hook_name/hook "$@"

if [ -e "$script_location"/$hook_name.local ]; then
	"$script_location"/$hook_name.local "$@"
fi

# Execute the pre-commit hooks to automatically get those validations
"$script_location"/pre-commit "$@"
