# This exposes the nvm-installed node and npm to non-user programs when the shell is opened
# If nvm updates node/npm, it will be updated on the next new shell
if command -v node &> /dev/null && command -v nvm &> /dev/null
then
	mkdir -p ~/bin

	ln -fs "`which npm`" ~/bin/npm
	ln -fs "`which node`" ~/bin/node

	if [[ ! -a /usr/local/bin/node ]]; then
		echo 'Creating /usr/local/bin/node'
		sudo ln -fs ~/bin/node /usr/local/bin/node
		sudo ln -fs ~/bin/npm /usr/local/bin/npm
	fi
fi

# Path to bundled scripts
PATH=$FZK_SCRIPT_FOLDER/bash:$FZK_SCRIPT_FOLDER/git:$PATH
# Convenient paths for common places I put scripts
PATH=node_modules/.bin:~/bin:$PATH

source $FZK_SCRIPT_FOLDER/zsh/config
source $FZK_SCRIPT_FOLDER/zsh/completions
$FZK_SCRIPT_FOLDER/macos/test-sudo-touch-id
source $FZK_SCRIPT_FOLDER/bash/aliases.txt
