#!/bin/sh

# To get auto-completion working, add the following line to .bash_profile or other bash config:
# complete -C "npm-install-pack --complete" npm-install-pack

set -e

move_pack() {
	pack=$1
	all_files=$(ls ../"$pack"/*.tgz)
	tgz_name=$(node -e "
		const files = \`$all_files\`.split(/\n/g).map(x => x.trim())
		const names = files
		.map(x => {
			const match = x.match(/\\/$pack\\/(.+?-.+?-(?:\\d+\\.){3}tgz)$/)
			if(match) {
				return match[1]
			}
			return null
		})
		.filter(Boolean)
		.sort()
		.reverse()

		console.log(names[0])
	")

	npm install --no-save ../"$pack"/"$tgz_name"
}

command=$1

if [ "$command" == "" ]; then
	echo 'Usage: npm-install-pack <dependency>'
	exit
fi

# Normalize pwd to the root
while [ "`pwd`" != '/' ]
do
	if [ -e "package.json" ]; then
		break
	else
		cd ..
	fi
done

if [ "$command" == "--complete" ]; then
	current=$3
	val=$(ls ../*/*.tgz)
	node -e "
		const files = \`$val\`.split(/\n/g).map(x => x.trim())
		const names = files
		.map(x => {
			const match = x.match(/\\/(.+?)\\/.+?-.+?-(\\d+\\.){3}tgz/)
			if(match) {
				return match[1]
			}
			return null
		})
		.filter(Boolean)
		.filter((x, i, a) => a.indexOf(x) === i)
		.filter(x => x.startsWith('$current'))

		console.log(names.join('\n'))
	"
	exit
fi

move_pack $1
