#!/bin/bash

# We test for ag (https://github.com/ggreer/the_silver_searcher) and use that if installed
if type ag >/dev/null 2>&1; then
	ag "$2" "$1" "${@: 3}"
else
	# Fallback that is much less performant
	find $1 -type f "${@: 3}" | xargs grep -iE "$2"
fi
